services:
  - type: web
    name: webbuilder-bot
    env: python
    region: singapore
    plan: free
    branch: main
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.9
