services:
  - type: web
    name: web-with-chikuu
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: MONGO_URI
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
      - key: ADMIN_ID
        sync: false
